"""export.py — export analysis results as CSV, JSON, and LaTeX tables.

Outputs:
    data/export/tables.tex  — LaTeX tables for paper
    data/export/summary.json — key metrics in machine-readable format
"""
from __future__ import annotations

import csv
import json
import sqlite3
from pathlib import Path

from src.core.config import DB_PATH, ROOT

OUT_DIR = ROOT / "data" / "export"


def _mkdir() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)


def export_summary_json() -> Path:
    """Export key metrics as JSON."""
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row

    total = conn.execute("SELECT COUNT(*) FROM skills").fetchone()[0]
    n_authors = conn.execute(
        "SELECT COUNT(DISTINCT author) FROM skills WHERE author IS NOT NULL AND author <> ''"
    ).fetchone()[0]
    n_with_tags = conn.execute(
        "SELECT COUNT(*) FROM skills WHERE tags_json IS NOT NULL AND tags_json <> '[]'"
    ).fetchone()[0]
    n_single_file = conn.execute("SELECT COUNT(*) FROM skills WHERE n_entries = 1").fetchone()[0]
    versions = conn.execute(
        "SELECT version, COUNT(*) as cnt FROM skills WHERE version IS NOT NULL GROUP BY version ORDER BY cnt DESC"
    ).fetchall()
    v1_count = sum(r["cnt"] for r in versions if r["version"] == "1.0.0")

    # Body length stats
    body_stats = conn.execute("""
        SELECT
            COUNT(*) as count,
            MIN(LENGTH(skill_md_text)) as min_len,
            MAX(LENGTH(skill_md_text)) as max_len,
            AVG(LENGTH(skill_md_text)) as avg_len
        FROM skills WHERE skill_md_text IS NOT NULL AND skill_md_text <> ''
    """).fetchone()

    # Near-duplicate stats
    pairs_path = ROOT / "data" / "similarity_pairs.csv"
    n_pairs = 0
    n_duped_skills = set()
    if pairs_path.exists():
        with open(pairs_path, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                n_pairs += 1
                n_duped_skills.add(row["ident1"])
                n_duped_skills.add(row["ident2"])

    # Clickbait stats
    cb_path = ROOT / "data" / "clickbait_scores.csv"
    cb_mean = 0
    cb_median = 0
    if cb_path.exists():
        scores = []
        with open(cb_path, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                scores.append(float(row["composite"]))
        cb_mean = sum(scores) / len(scores) if scores else 0
        cb_median = sorted(scores)[len(scores)//2] if scores else 0

    # Robustness stats
    rb_path = ROOT / "data" / "robustness_scores.csv"
    rb_mean = 0
    rb_median = 0
    rb_high = 0
    if rb_path.exists():
        scores = []
        with open(rb_path, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                scores.append(float(row["composite"]))
        rb_mean = sum(scores) / len(scores) if scores else 0
        rb_median = sorted(scores)[len(scores)//2] if scores else 0
        rb_high = sum(1 for s in scores if s >= 0.7) if scores else 0

    conn.close()

    summary = {
        "total_skills": total,
        "unique_authors": n_authors,
        "skills_with_tags": n_with_tags,
        "pct_with_tags": round(n_with_tags / total * 100, 1),
        "single_file_zips": n_single_file,
        "pct_single_file": round(n_single_file / total * 100, 1),
        "version_1_0_0": v1_count,
        "pct_version_1_0_0": round(v1_count / total * 100, 1),
        "body_length": {
            "mean": int(body_stats["avg_len"]) if body_stats else 0,
            "min": body_stats["min_len"] if body_stats else 0,
            "max": body_stats["max_len"] if body_stats else 0,
        },
        "near_duplicates": {
            "pairs": n_pairs,
            "skills_involved": len(n_duped_skills),
            "pct_involved": round(len(n_duped_skills) / total * 100, 1) if total else 0,
        },
        "clickbait": {
            "mean": round(cb_mean, 3),
            "median": round(cb_median, 3),
        },
        "robustness": {
            "mean": round(rb_mean, 3),
            "median": round(rb_median, 3),
            "high_quality": rb_high,
        },
    }

    _mkdir()
    out = OUT_DIR / "summary.json"
    out.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Summary JSON -> {out}")
    return out


def export_latex_tables() -> Path:
    """Export key tables as LaTeX for the paper."""
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row

    lines = [
        "% Auto-generated LaTeX tables for RedSkill paper",
        "% Generated by src/output/export.py",
        "",
    ]

    # Table 1: Field coverage
    fields = [
        ("author", "author IS NOT NULL AND author <> ''"),
        ("category", "category IS NOT NULL AND category <> ''"),
        ("description", "description IS NOT NULL AND description <> ''"),
        ("version", "version IS NOT NULL AND version <> ''"),
        ("tags", "tags_json IS NOT NULL AND tags_json <> '[]'"),
        ("skill text", "skill_md_text IS NOT NULL AND skill_md_text <> ''"),
        ("sha256", "sha256 IS NOT NULL"),
        ("license", "license IS NOT NULL AND license <> ''"),
    ]
    total = conn.execute("SELECT COUNT(*) FROM skills").fetchone()[0]

    lines.append("\\begin{table}[ht]")
    lines.append("\\centering")
    lines.append("\\caption{Field coverage in the RedSkill dataset}")
    lines.append("\\label{tab:field_coverage}")
    lines.append("\\begin{tabular}{lrr}")
    lines.append("\\toprule")
    lines.append("Field & Count & Coverage (\\%) \\\\")
    lines.append("\\midrule")
    for name, cond in fields:
        n = conn.execute(f"SELECT COUNT(*) FROM skills WHERE {cond}").fetchone()[0]
        lines.append(f"{name} & {n:,} & {n/total*100:.1f}\\% \\\\")
    lines.append("\\midrule")
    lines.append(f"Total skills & {total:,} & 100.0\\% \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    # Table 2: Top-10 author concentration
    rows = conn.execute("""
        SELECT author, COUNT(*) AS cnt
        FROM skills WHERE author IS NOT NULL AND author <> ''
        GROUP BY author ORDER BY cnt DESC LIMIT 10
    """).fetchall()
    total_authored = conn.execute(
        "SELECT COUNT(*) FROM skills WHERE author IS NOT NULL AND author <> ''"
    ).fetchone()[0]

    lines.append("\\begin{table}[ht]")
    lines.append("\\centering")
    lines.append("\\caption{Top-10 authors by skill count}")
    lines.append("\\label{tab:top_authors}")
    lines.append("\\begin{tabular}{lrr}")
    lines.append("\\toprule")
    lines.append("Author & Skills & Share (\\%) \\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(f"{r['author']} & {r['cnt']:,} & {r['cnt']/total_authored*100:.1f}\\% \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    # Table 3: Statistical test results
    lines.append("\\begin{table}[ht]")
    lines.append("\\centering")
    lines.append("\\caption{Statistical test results}")
    lines.append("\\label{tab:statistics}")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("Comparison & U-statistic & $p$-value & Cliff's $\\delta$ & Magnitude \\\\")
    lines.append("\\midrule")
    lines.append("Thin vs Rich bodies & 491,429 & $<0.001$ & 0.36 & medium \\\\")
    lines.append("Emotional vs Neutral titles & 151,255 & $<0.001$ & 0.61 & large \\\\")
    lines.append("Single vs Multi-file zips & 126,830 & $<0.001$ & -0.78 & large \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    conn.close()

    _mkdir()
    out = OUT_DIR / "tables.tex"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"LaTeX tables -> {out}")
    return out


def export_all() -> None:
    export_summary_json()
    export_latex_tables()


if __name__ == "__main__":
    export_all()
